[workspace]
authors = ["Trim Bresilla <trim.bresilla@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
name = "rosy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop-full = ">=0.10.0,<0.11"
ros-humble-vision-msgs = ">=4.1.1,<5"
ros-humble-ackermann-msgs = ">=2.0.2,<3"
ros-humble-rmw-fastrtps-cpp = ">=6.2.7,<7"
ros-humble-rmw = ">=6.1.2,<7"
ros-humble-rmw-cyclonedds-cpp = ">=1.3.4,<2"
ros-humble-rclpy = ">=3.3.15,<4"
